In [131]:
import numpy as np

In [132]:
a = np.array([[3, 1, 2]])
b = np.array([[5, 6, 5]])
c = np.array([[7, 10, 0, 9]])

print(a)
print(b)
print(c)

[[3 1 2]]
[[5 6 5]]
[[ 7 10  0  9]]


ADDING AND REMOVING ELEMENTS

In [133]:
concat_row = np.concatenate((a, b, c), axis=1)
concat_row

array([[ 3,  1,  2,  5,  6,  5,  7, 10,  0,  9]])

In [134]:
concat_column = np.concatenate((a, b), axis=0) 
concat_column

array([[3, 1, 2],
       [5, 6, 5]])

In [135]:
unmatch_concat_column = np.concatenate((a, b, c), axis=0) 
unmatch_concat_column

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 2 has size 4

In [136]:
a = np.insert(a, 1, 4, axis=1)
a

array([[3, 4, 1, 2]])

In [137]:
b = np.insert(b, 3, 8, axis=1)
b

array([[5, 6, 5, 8]])

In [138]:
unmatch_concat_column = np.concatenate((a, b, c), axis=0) 
unmatch_concat_column

array([[ 3,  4,  1,  2],
       [ 5,  6,  5,  8],
       [ 7, 10,  0,  9]])

In [139]:
np.append(a, [[12]], axis=1)

array([[ 3,  4,  1,  2, 12]])

In [140]:
np.delete(c, 3, axis=1)

array([[ 7, 10,  0]])

SORT

In [141]:
concat_row.sort()
concat_row

array([[ 0,  1,  2,  3,  5,  5,  6,  7,  9, 10]])

In [142]:
unmatch_concat_column.sort()
unmatch_concat_column

array([[ 1,  2,  3,  4],
       [ 5,  5,  6,  8],
       [ 0,  7,  9, 10]])

SHAPE

In [143]:
unmatch_concat_column.shape

(3, 4)

In [144]:
unmatch_concat_column.size

12

In [145]:
unmatch_concat_column.ndim

2

RESHAPE

In [146]:
d = np.array([11, 12, 13, 14, 15, 16])

print(d)
print(d.ndim)

[11 12 13 14 15 16]
1


In [147]:
d.reshape(2, 3)

array([[11, 12, 13],
       [14, 15, 16]])

INDEXING AND SLICING

In [148]:
print(d[:3])
print(d[3:])
print(d[-2])

[11 12 13]
[14 15 16]
15


In [149]:
print(unmatch_concat_column)
print('************************')
print(unmatch_concat_column[2:])
print('************************')
print(unmatch_concat_column[:-1])
print('************************')
print(unmatch_concat_column[unmatch_concat_column<5])
print('************************')
print(unmatch_concat_column[unmatch_concat_column%2==0])
print('************************')
print(unmatch_concat_column[unmatch_concat_column==5])
print('************************')
print(np.nonzero(unmatch_concat_column<5))

[[ 1  2  3  4]
 [ 5  5  6  8]
 [ 0  7  9 10]]
************************
[[ 0  7  9 10]]
************************
[[1 2 3 4]
 [5 5 6 8]]
************************
[1 2 3 4 0]
************************
[ 2  4  6  8  0 10]
************************
[5 5]
************************
(array([0, 0, 0, 0, 2], dtype=int64), array([0, 1, 2, 3, 0], dtype=int64))


ARRAY FROM EXISTING DATA

In [150]:
tmp_list = [1, 2, 3]
type(tmp_list)

list

In [151]:
list_to_array = np.array(tmp_list)
list_to_array

array([1, 2, 3])

In [152]:
np.vstack((list_to_array,a,b))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 4

In [153]:
np.hstack((a,b))

array([[3, 4, 1, 2, 5, 6, 5, 8]])

In [154]:
np.hsplit(concat_row, 5)

[array([[0, 1]]),
 array([[2, 3]]),
 array([[5, 5]]),
 array([[6, 7]]),
 array([[ 9, 10]])]

TRANSPOSE

In [155]:
unmatch_concat_column

array([[ 1,  2,  3,  4],
       [ 5,  5,  6,  8],
       [ 0,  7,  9, 10]])

In [156]:
unmatch_concat_column.T

array([[ 1,  5,  0],
       [ 2,  5,  7],
       [ 3,  6,  9],
       [ 4,  8, 10]])