In [2]:
import numpy as np

First we create some 2D arrays

In [3]:
a = np.array([[3, 1, 2]])
b = np.array([[5, 6, 5]])
c = np.array([[7, 10, 0, 9]])

print(a)
print(b)
print(c)

[[3 1 2]]
[[5 6 5]]
[[ 7 10  0  9]]


ADDING AND REMOVING ELEMENTS

We can use concatenate to merge multiple arrays into a NEW array

In [4]:
concat_row = np.concatenate((a, b, c), axis=1)
concat_row

array([[ 3,  1,  2,  5,  6,  5,  7, 10,  0,  9]])

We can do it to create a matrix-style array....

In [5]:
concat_column = np.concatenate((a, b), axis=0)
concat_column

array([[3, 1, 2],
       [5, 6, 5]])

.... but they must have the same number of dimensions

In [6]:
unmatch_concat_column = np.concatenate((a, b, c), axis=0)
unmatch_concat_column

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 2 has size 4

We can add elements in an specific index, creating a NEW array

In [7]:
a = np.insert(a, 1, 4, axis=1)
a

array([[3, 4, 1, 2]])

In [8]:
b = np.insert(b, 3, 8, axis=1)
b

array([[5, 6, 5, 8]])

Here we concat the new arrays, which have the same dimensions

In [9]:
unmatch_concat_column = np.concatenate((a, b, c), axis=0)
unmatch_concat_column

array([[ 3,  4,  1,  2],
       [ 5,  6,  5,  8],
       [ 7, 10,  0,  9]])

Append will add a new element to the last index of the array, like it works on the lists

In [10]:
np.append(a, [[12]], axis=1)

array([[ 3,  4,  1,  2, 12]])

Delete removes the element on the given index

In [11]:
np.delete(c, 3, axis=1)

array([[ 7, 10,  0]])

SORT

In [12]:
concat_row.sort()
concat_row

array([[ 0,  1,  2,  3,  5,  5,  6,  7,  9, 10]])

When we sort a matrix-style array, the sorting will be applied on each element individually

In [13]:
unmatch_concat_column.sort()
unmatch_concat_column

array([[ 1,  2,  3,  4],
       [ 5,  5,  6,  8],
       [ 0,  7,  9, 10]])

SHAPE

In [14]:
unmatch_concat_column.shape # Dimensions, elements and columns of the array

(3, 4)

In [15]:
unmatch_concat_column.size # Elements of the array

12

In [16]:
unmatch_concat_column.ndim # Dimensions of the array

2

RESHAPE

In [17]:
d = np.array([11, 12, 13, 14, 15, 16]) # 1D array

print(d)
print(d.ndim)

[11 12 13 14 15 16]
1


We can alter the structutre of the array, but the result must be (n x n) on his columns and dimensions

In [18]:
d.reshape(2, 3)

array([[11, 12, 13],
       [14, 15, 16]])

INDEXING AND SLICING

The slicing works like it does on list elements

In [19]:
print(d[:3])
print(d[3:])
print(d[-2])

[11 12 13]
[14 15 16]
15


We can do this slicing using logical operators

In [54]:
print(unmatch_concat_column)
print('************************')
print(unmatch_concat_column[2:])
print('************************')
print(unmatch_concat_column[:-1])
print('************************')
print(unmatch_concat_column[unmatch_concat_column<5])
print('************************')
print(unmatch_concat_column[unmatch_concat_column%2==0])
print('************************')
print(unmatch_concat_column[unmatch_concat_column==5])
print('************************')
nz=np.nonzero(unmatch_concat_column<5)
nz
list(zip(nz[0],nz[1]))
for x,y in list(zip(nz[0],nz[1])):
    unmatch_concat_column[x,y]

[[ 1  2  3  4]
 [ 5  5  6  8]
 [ 0  7  9 10]]
************************
[[ 0  7  9 10]]
************************
[[1 2 3 4]
 [5 5 6 8]]
************************
[1 2 3 4 0]
************************
[ 2  4  6  8  0 10]
************************
[5 5]
************************


(array([0, 0, 0, 0, 2], dtype=int64), array([0, 1, 2, 3, 0], dtype=int64))

[(0, 0), (0, 1), (0, 2), (0, 3), (2, 0)]

1

2

3

4

0

ARRAY FROM EXISTING DATA

In [21]:
tmp_list = [1, 2, 3]
type(tmp_list)

list

We can set elements into a NumPy array and work with other arrays

In [22]:
list_to_array = np.array(tmp_list)
list_to_array

array([1, 2, 3])

As long as they have the same dimensions, we can give them the matrix-style format

In [23]:
np.vstack((list_to_array,a,b))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 4

Or just like an array

In [24]:
np.hstack((a,b))

array([[3, 4, 1, 2, 5, 6, 5, 8]])

We can split NumPy arrays into smaller NumPy arrays, as long as each one of them can have the same number of elements

In [25]:
np.hsplit(concat_row, 5)

[array([[0, 1]]),
 array([[2, 3]]),
 array([[5, 5]]),
 array([[6, 7]]),
 array([[ 9, 10]])]

TRANSPOSE

In [26]:
unmatch_concat_column

array([[ 1,  2,  3,  4],
       [ 5,  5,  6,  8],
       [ 0,  7,  9, 10]])

In [27]:
unmatch_concat_column.T

array([[ 1,  5,  0],
       [ 2,  5,  7],
       [ 3,  6,  9],
       [ 4,  8, 10]])