In [1]:
# Multiple outputs per cell in Jupyter 
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
import numpy as np

In [35]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5, 6])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

(a.ndim, a.shape, a)
(b.ndim, b.shape, b)
(c.ndim, c.shape, c)
(d.ndim, d.shape, d)

(0, (), array(42))

(1, (6,), array([1, 2, 3, 4, 5, 6]))

(2,
 (2, 3),
 array([[1, 2, 3],
        [4, 5, 6]]))

(3,
 (2, 2, 3),
 array([[[1, 2, 3],
         [4, 5, 6]],
 
        [[1, 2, 3],
         [4, 5, 6]]]))

In [86]:
np_array_2d = np.arange(0, 6).reshape([2,3])
np_array_2d
np.sum(np_array_2d)
"+",np_array_2d[0,:]+np_array_2d[1,:]
"sum",np.sum(np_array_2d, axis = 0)

"+",np_array_2d[:,0]+np_array_2d[:,1]+np_array_2d[:,2]
"sum",np.sum(np_array_2d, axis = 1)

array([[0, 1, 2],
       [3, 4, 5]])

15

('+', array([3, 5, 7]))

('sum', array([3, 5, 7]))

('+', array([ 3, 12]))

('sum', array([ 3, 12]))

In [89]:
b.shape, b
v = b[np.newaxis,:]
v.shape, v

((6,), array([1, 2, 3, 4, 5, 6]))

((1, 6), array([[1, 2, 3, 4, 5, 6]]))

In [90]:
b.shape, b
v = b[:, np.newaxis]
v.shape, v

((6,), array([1, 2, 3, 4, 5, 6]))

((6, 1),
 array([[1],
        [2],
        [3],
        [4],
        [5],
        [6]]))

In [91]:
v=b.reshape((1,6))
v.shape, v

((1, 6), array([[1, 2, 3, 4, 5, 6]]))

In [92]:
v=b.reshape((6,1))
v.shape, v

((6, 1),
 array([[1],
        [2],
        [3],
        [4],
        [5],
        [6]]))

In [93]:
v=np.expand_dims(b, axis=0)
v.shape, v

((1, 6), array([[1, 2, 3, 4, 5, 6]]))

In [94]:
v=np.expand_dims(b, axis=1)
v.shape,v

((6, 1),
 array([[1],
        [2],
        [3],
        [4],
        [5],
        [6]]))

In [101]:
c
c[1,:]
# c[1:c.shape[0],0:c.shape[1]]
# c[1:,:]
c[1:]
c[:,1]
c[:1]

array([[1, 2, 3],
       [4, 5, 6]])

array([4, 5, 6])

array([[4, 5, 6]])

array([2, 5])

array([[1, 2, 3]])

In [105]:
b
"CONCATENATE", np.concatenate((b,b),axis=0)
np.hstack((b,b))
# np.concatenate((b,b),axis=1)
np.vstack((b,b))
print("=== c")
c
np.hstack((c,c))
np.vstack((c,c))

array([1, 2, 3, 4, 5, 6])

('CONCATENATE', array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]))

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

=== c


array([[1, 2, 3],
       [4, 5, 6]])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])